# Generated by Django 3.2.4 on 2021-06-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlAccount',
            fields=[
                ('account_number', models.IntegerField(primary_key=True, serialize=False)),
                ('account_name', models.TextField()),
                ('account_code', models.CharField(choices=[('A', 'Assets'), ('L', 'Liabilities'), ('R', 'Revenues'), ('E', 'Expenses'), ('EQ', 'Equity'), ('N/A', 'None')], default='N/A', max_length=4)),
                ('account_description', models.TextField()),
                ('is_debit', models.BooleanField()),
                ('is_a_parent', models.BooleanField(default=False)),
                ('parent', models.BigIntegerField(blank=True)),
            ],
        ),
    ]
